# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for detail
version: "2"

# Requirements are based on build_env.Dockerfile

# Set the OS, Python version and other tools you might need
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  apt_packages:
    - "build-essential"
    - "flex"
    - "bison"
    - xxd
    # Python3 with pip (thus wheel), and presumably python3-venv, are already installed.
    - libosmesa6 # for easier opengl renders
    # dependencies for browsers https://github.com/Davide-sd/sphinx_k3d_screenshot/blob/main/.readthedocs.yml
    - bzip2
    - libxtst6
    - libgtk-3-0
    - libx11-xcb-dev
    - libdbus-glib-1-2
    - libxt6
    - libpci-dev
    - libasound2
    - libnss3
    - libgbm-dev
  jobs:
    post_create_environment:
      - pip install auditwheel patchelf
    pre_install:
      - echo "pre install, make it"
      - DONT_RUN_SPHINX=1 RUN_DIRECT=1 BUILD_IN_PLACE=1 bash testing/linux/build-docs.bash
      - echo "--find-links=bin/ eden-simulator" >  bin/eden_wheel_requirements.txt

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
  

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
  - requirements: docs/requirements.txt
  # Install our python package before building the docs
  # use a requirements file because it's not easy to get VERSION for the whl file
  # https://stackoverflow.com/questions/48183160/how-to-pip-install-whl-on-windows-using-a-wildcard/52481267#52481267
  - requirements: bin/eden_wheel_requirements.txt
